# Generated by Django 3.0.4 on 2020-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='profile_image')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(blank=True, max_length=3)),
                ('cidade_desaparecimento', models.CharField(max_length=50)),
                ('estado_desaparecimento', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Perdido'), (2, 'Comunicado'), (3, 'Encontrado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.IntegerField(blank=True, max_length=9)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
