# Generated by Django 3.0.4 on 2020-03-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200314_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Animal'),
        ),
    ]
