# Generated by Django 3.0.4 on 2020-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200313_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cidade_desaparecimento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado_desaparecimento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
