# Generated by Django 3.0.4 on 2020-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200314_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='informacoes_extras',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
