# Generated by Django 3.0.4 on 2020-03-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_animal_informacoes_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Perdido'), (2, 'Comunicado'), (3, 'Encontrado')], default=1),
        ),
    ]
