# Generated by Django 3.0.4 on 2020-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200316_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cidade_desaparecimento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado_desaparecimento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
