# Generated by Django 3.0.4 on 2020-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200316_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
